name=ssd1306xled
version=1.0.0
author=Neven Boyanov, Tejashwi Kalp Taru, David Johnson-Davies
maintainer=Tejashwi Kalp Taru
sentence=SSD1306, SSD1315 or SSH1106 OLED screen driver
paragraph=Lightweight library for ATtiny85 and other AVR microcontrollers with I2C support for 128x64 and 128x32 displays.
category=Display
url=https://github.com/tejashwikalptaru/ssd1306xled
architectures=*
depends=